name: Release
on: [workflow_dispatch]
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-24.04-arm, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - run: sbt assembly
      - if: matrix.os != 'windows-latest'
        run: echo "VERSION=$(sbt -batch -error 'print version' | head -n 1)" >> $GITHUB_ENV
      - if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $version = (sbt -batch -error "print version" | Select-Object -First 1).Trim()
          echo "VERSION=$version" >> $env:GITHUB_ENV
      - if: matrix.os == 'macos-latest'
        run: |
         jpackage --input target/scala-2.13 \
           --main-jar pingrpc-assembly-${{ env.VERSION }}.jar \
           --type dmg \
           --icon src/main/resources/icon.icns \
           --app-version ${{ env.VERSION }} \
           --name pingrpc
      - if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm'
        run: |
         jpackage --input target/scala-2.13 \
           --main-jar pingrpc-assembly-${{ env.VERSION }}.jar \
           --type deb \
           --icon src/main/resources/icon.icns \
           --app-version ${{ env.VERSION }} \
           --name pingrpc
      - if: matrix.os == 'windows-latest'
        run: |
         jpackage --input target/scala-2.13 `
           --main-jar pingrpc-assembly-${{ env.VERSION }}.jar `
           --type exe `
           --app-version ${{ env.VERSION }} `
           --name pingrpc `
      - if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: pingrpc-arm64.dmg
          path: pingrpc-${{ env.VERSION }}.dmg
      - if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: pingrpc-amd64.deb
          path: pingrpc_${{ env.VERSION }}_amd64.deb
      - if: matrix.os == 'ubuntu-24.04-arm'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: pingrpc-arm64.deb
          path: pingrpc_${{ env.VERSION }}_arm64.deb
      - if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: pingrpc.exe
          path: pingrpc-${{ env.VERSION }}.exe
